namespace SpriteKind {
    export const text = SpriteKind.create()
    export const NO_alternative = SpriteKind.create()
    export const YES_alternative = SpriteKind.create()
    export const Bonnie_alternative = SpriteKind.create()
    export const Freddy_alternative = SpriteKind.create()
    export const Chica_alternative = SpriteKind.create()
    export const Foxy_alternative = SpriteKind.create()
    export const MY_age = SpriteKind.create()
    export const why = SpriteKind.create()
    export const Ally = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        .......111.......
        .111..1fff1..111.
        1eee111fff111eee1
        1e44eefffffee44e1
        1e4eeeeeeeeeee4e1
        .1eefffeeefffee1.
        ..1f181fef181f1..
        .1ef111fef111fe1.
        .1ef111fef111fe1.
        .14444fffff44441.
        144f444fff444f441
        14f44444444444f41
        1444f4444444f4441
        .1f11f11f11f11f1.
        .1fffffffffffff1.
        .1f11f11f11f11f1.
        .1eeeeeeeeeeeee1.
        ..1eeeeeeeeeee1..
        ...11111111111...
        `)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NO_alternative, function (sprite, otherSprite) {
    sprites.destroy(mySprite3)
    sprites.destroy(mySprite4)
    mySprite2.sayText("That's a schame.", 2000, true)
    pause(3000)
    mySprite2.sayText("")
    pause(5000)
    mySprite2.sayText("Are you by any chance under 12", 2000, true)
    pause(3000)
    mySprite3 = sprites.create(img`
        1.........................
        1..11...........1111111111
        1.11....................1.
        1.1....................1..
        1......................1..
        1..1..................1...
        1..1.111.111..........1...
        1..11...1...1........1....
        1..1....1...1.......1.....
        1..1....1...1.......1.....
        1..1....1...1......1......
        1..1....1...1.....1.......
        1..1....1...1.....1.......
        1..1....1...1....1........
        1..1....1...1...1.........
        1..1....1...1...1.........
        `, SpriteKind.MY_age)
    mySprite4 = sprites.create(img`
        . . 1 1 1 1 1 1 1 1 . . 
        . 1 . . . . . . . . 1 . 
        1 . . . . . . . . . . 1 
        1 . . . . . . . . . . 1 
        1 . . . . . . . . . . 1 
        . . . . . . . . . . 1 . 
        . . . . . . . . . 1 . . 
        . . . . . . . . 1 . . . 
        . . . . . . . 1 . . . . 
        . . . . . . 1 . . . . . 
        . . . . . 1 . . . . . . 
        . . . . . 1 . . . . . . 
        . . . . . 1 . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . 1 . . . . . . 
        `, SpriteKind.why)
    mySprite3.setPosition(60, 110)
    mySprite4.setPosition(110, 110)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.YES_alternative, function (sprite, otherSprite) {
    sprites.destroy(mySprite3)
    sprites.destroy(mySprite4)
    mySprite2.sayText("Right...", 2000, true)
    pause(3000)
    mySprite2.sayText("So who is you favorit?", 2000, true)
    pause(3000)
    mySprite3 = sprites.create(img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . 1 1 . . . . . 
        . . . . 1 f f 1 . . . . 
        . e e e 1 f f 1 e e e . 
        . e e e f f f f e e e . 
        . e e e e e e e e e e . 
        . . e e e e e e e e . . 
        . e e e e e e e e e e . 
        . e e e f f e e f f e . 
        . e e e f f e e f f e . 
        . e e e e e e e e e e . 
        . e e e e e f f f e e . 
        . e e e e e e f e e e . 
        . e e e e e e e e e e . 
        . . e e e f f e f f 1 . 
        . . . e e e f f f 1 . . 
        . . . . . 1 f f f 1 . . 
        . . . . 1 f f 1 f f 1 . 
        . . . . . 1 1 . 1 1 . . 
        `, SpriteKind.Freddy_alternative)
    mySprite4 = sprites.create(img`
        . . . . . . . . . . . . 
        . . . . . . . 6 6 . . . 
        . 6 6 6 . . . 6 6 . . . 
        . 6 6 6 6 . . 6 6 . . . 
        . . 6 6 6 . . 6 6 . . . 
        . . . 6 6 . . 6 6 . . . 
        . . . 6 6 6 6 6 6 . . . 
        . . 6 6 6 6 6 6 6 6 . . 
        . 6 6 6 6 6 6 6 6 6 6 . 
        . 6 6 6 f f 6 6 f f 6 . 
        . 6 6 6 f f 6 6 f f 6 . 
        . 6 6 6 6 6 6 6 6 6 6 . 
        . 6 6 6 6 6 f f f 6 6 . 
        . 6 6 6 6 6 6 f 6 6 6 . 
        . 6 6 6 6 6 6 6 6 6 6 . 
        . . 6 6 6 2 2 6 2 2 . . 
        . . . 6 6 6 2 2 2 . . . 
        . . . . . . 2 2 2 . . . 
        . . . . . 2 2 . 2 2 . . 
        . . . . . . . . . . . . 
        `, SpriteKind.Bonnie_alternative)
    mySprite5 = sprites.create(img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . 5 5 5 5 5 5 . . . 
        . . 5 5 5 5 5 5 5 5 . . 
        . 5 5 5 5 5 5 5 5 5 5 . 
        . 5 5 5 f f 5 5 f f 5 . 
        . 5 5 5 f f 5 5 f f 5 . 
        . 5 5 5 5 5 5 5 5 5 5 . 
        . 5 5 5 5 4 4 4 4 4 4 . 
        . 5 5 5 4 4 4 4 4 4 4 4 
        . 5 5 5 5 4 4 4 4 4 4 4 
        . . 5 5 5 1 5 1 5 1 5 . 
        . . . 5 5 5 5 5 5 . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `, SpriteKind.Chica_alternative)
    mySprite6 = sprites.create(img`
        . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . 
        . 2 2 2 . . . . 2 2 2 . . . 
        . 2 2 2 . . . . 2 2 2 . . . 
        . 2 2 2 2 2 2 f 2 2 2 . . . 
        . . 2 2 2 2 2 f 2 2 . . . . 
        . 2 2 2 2 2 f 2 2 2 2 . . . 
        . 2 2 2 f f 2 2 f f 2 . . . 
        . 2 2 f f f 2 2 f f 2 . . . 
        . 2 f 2 2 2 2 2 2 2 2 . . . 
        . f 2 2 2 2 2 2 2 2 f 2 . . 
        . 2 2 2 2 2 2 2 2 2 2 2 2 . 
        . 2 2 2 2 2 2 2 2 2 2 2 2 . 
        . . 2 2 2 2 2 2 2 2 2 2 2 . 
        . . . 2 2 2 2 2 2 2 2 2 2 . 
        . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . 
        `, SpriteKind.Foxy_alternative)
    mySprite3.setPosition(30, 110)
    mySprite4.setPosition(60, 110)
    mySprite5.setPosition(90, 110)
    mySprite6.setPosition(120, 110)
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    mySprite.setImage(img`
        .......111.......
        .111..1fff1..111.
        1eee111fff111eee1
        1e44eefffffee44e1
        1e4eeeeeeeeeee4e1
        .1eefffeeefffee1.
        ..1f111fef111f1..
        .1ef181fef181fe1.
        .1ef111fef111fe1.
        .14444fffff44441.
        144f444fff444f441
        14f44444444444f41
        1444f4444444f4441
        .1f11f11f11f11f1.
        .1fffffffffffff1.
        .1f11f11f11f11f1.
        .1eeeeeeeeeeeee1.
        ..1eeeeeeeeeee1..
        ...11111111111...
        `)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        .......111.......
        .111..1fff1..111.
        1eee111fff111eee1
        1e44eefffffee44e1
        1e4eeeeeeeeeee4e1
        .1eefffeeefffee1.
        ..1f111fef111f1..
        .1ef811fef811fe1.
        .1ef111fef111fe1.
        .14444fffff44441.
        144f444fff444f441
        14f44444444444f41
        1444f4444444f4441
        .1f11f11f11f11f1.
        .1fffffffffffff1.
        .1f11f11f11f11f1.
        .1eeeeeeeeeeeee1.
        ..1eeeeeeeeeee1..
        ...11111111111...
        `)
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    mySprite.setImage(img`
        .......111.......
        .111..1fff1..111.
        1eee111fff111eee1
        1e44eefffffee44e1
        1e4eeeeeeeeeee4e1
        .1eefffeeefffee1.
        ..1f111fef111f1..
        .1ef181fef181fe1.
        .1ef111fef111fe1.
        .14444fffff44441.
        144f444fff444f441
        14f44444444444f41
        1444f4444444f4441
        .1f11f11f11f11f1.
        .1fffffffffffff1.
        .1f11f11f11f11f1.
        .1eeeeeeeeeeeee1.
        ..1eeeeeeeeeee1..
        ...11111111111...
        `)
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    mySprite.setImage(img`
        .......111.......
        .111..1fff1..111.
        1eee111fff111eee1
        1e44eefffffee44e1
        1e4eeeeeeeeeee4e1
        .1eefffeeefffee1.
        ..1f111fef111f1..
        .1ef181fef181fe1.
        .1ef111fef111fe1.
        .14444fffff44441.
        144f444fff444f441
        14f44444444444f41
        1444f4444444f4441
        .1f11f11f11f11f1.
        .1fffffffffffff1.
        .1f11f11f11f11f1.
        .1eeeeeeeeeeeee1.
        ..1eeeeeeeeeee1..
        ...11111111111...
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        .......111.......
        .111..1fff1..111.
        1eee111fff111eee1
        1e44eefffffee44e1
        1e4eeeeeeeeeee4e1
        .1eefffeeefffee1.
        ..1f111fef111f1..
        .1ef118fef118fe1.
        .1ef111fef111fe1.
        .14444fffff44441.
        144f444fff444f441
        14f44444444444f41
        1444f4444444f4441
        .1f11f11f11f11f1.
        .1fffffffffffff1.
        .1f11f11f11f11f1.
        .1eeeeeeeeeeeee1.
        ..1eeeeeeeeeee1..
        ...11111111111...
        `)
})
controller.up.onEvent(ControllerButtonEvent.Released, function () {
    mySprite.setImage(img`
        .......111.......
        .111..1fff1..111.
        1eee111fff111eee1
        1e44eefffffee44e1
        1e4eeeeeeeeeee4e1
        .1eefffeeefffee1.
        ..1f111fef111f1..
        .1ef181fef181fe1.
        .1ef111fef111fe1.
        .14444fffff44441.
        144f444fff444f441
        14f44444444444f41
        1444f4444444f4441
        .1f11f11f11f11f1.
        .1fffffffffffff1.
        .1f11f11f11f11f1.
        .1eeeeeeeeeeeee1.
        ..1eeeeeeeeeee1..
        ...11111111111...
        `)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        .......111.......
        .111..1fff1..111.
        1eee111fff111eee1
        1e44eefffffee44e1
        1e4eeeeeeeeeee4e1
        .1eefffeeefffee1.
        ..1f111fef111f1..
        .1ef111fef111fe1.
        .1ef181fef181fe1.
        .14444fffff44441.
        144f444fff444f441
        14f44444444444f41
        1444f4444444f4441
        .1f11f11f11f11f1.
        .1fffffffffffff1.
        .1f11f11f11f11f1.
        .1eeeeeeeeeeeee1.
        ..1eeeeeeeeeee1..
        ...11111111111...
        `)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Freddy_alternative, function (sprite, otherSprite) {
    sprites.destroy(mySprite3)
    sprites.destroy(mySprite4)
    sprites.destroy(mySprite5)
    sprites.destroy(mySprite6)
    mySprite2.sayText("Yooooour basic arn't you?", 3000, true)
    pause(4000)
    mySprite2.sayText("What?", 500, true)
    pause(1000)
    mySprite2.sayText("Is it my fault that your favorit is lame", 2500, true)
    pause(3500)
    the_REAL_Freddy.setVelocity(25, 0)
})
let mySprite6: Sprite = null
let mySprite5: Sprite = null
let mySprite4: Sprite = null
let mySprite3: Sprite = null
let the_REAL_Freddy: Sprite = null
let mySprite: Sprite = null
let mySprite2: Sprite = null
scene.setBackgroundColor(15)
mySprite2 = sprites.create(img`
    ...........................cccccccccc..........................
    .........................cccaaaaaaaaccc........................
    ........................ccaaaaaaaaaaaacc.......................
    .......................ccaaaaaaaaaaaaaacc......................
    ......................ccaaaaaaaaaaaaaaaacc.....................
    ......................caaaaaaaaaaaaaaaaaac.....................
    .....................ccaaaaaaaaaaaaaaaaaacc....................
    .....................ccaaaaaaaaaaaaaaaaaaac....................
    .....................caaaaaaaaaaaaaaaaaaaac....................
    ....................ccaaaaaaaaaaaaaaaaaaaacc...................
    ....................ccaaaffffaaaaaffffaaaacc...................
    ....................ccaaaff1faaaaaff1faaaaac...................
    ....................ccaaaf1ffaaaaaf1ffaaaaac...................
    ....................ccaaaffffaaaaaffffaaaaac...................
    ....................ccaaaaaaaaaaaaaaaaaaaaac...................
    ....................ccaaaaaaaaaaaaaaaaaaaaac...................
    .....................caaaaaaaaaaaaaaaaaaaaac...................
    .....................cfaafffffffffffffaaaacc...................
    .....................cfaafffffffffffffaaaacc...................
    .....................cfaafffffffffffffaaccccc..................
    ....................ccffaaafffffffffaaaccaaacc.................
    ....................caaffaaaaaaaaaaaaaacfaaccccc...............
    ...................ccaaaffaaaaaaaaaaaaffaaacccccc..............
    ...................acaaaafffaaaaaaaaffaaaaacccccc..............
    ..................caccaaaaafffffffffffaaaaaaccccca.............
    ..................caacaaaaaaaa55555555aaaaaaccccca.............
    .................ccaacaaaaaaaa55555555aaaaaaccccca.............
    ................ccaaacaaaaaaaaaa5555aaaaaaaaccccca.............
    ...............ccaaaacaaaaaaaaaaaaaaaaaaaaaacccccca............
    ...............caaaacaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............ccaaaccaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............caccccaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaa.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaaaacccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ................ccccaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaa..........
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    `, SpriteKind.Enemy)
animation.runImageAnimation(
mySprite2,
[img`
    ...........................cccccccccc..........................
    .........................cccaaaaaaaaccc........................
    ........................ccaaaaaaaaaaaacc.......................
    .......................ccaaaaaaaaaaaaaacc......................
    ......................ccaaaaaaaaaaaaaaaacc.....................
    ......................caaaaaaaaaaaaaaaaaac.....................
    .....................ccaaaaaaaaaaaaaaaaaacc....................
    .....................ccaaaaaaaaaaaaaaaaaaac....................
    .....................caaaaaaaaaaaaaaaaaaaac....................
    ....................ccaaaaaaaaaaaaaaaaaaaacc...................
    ....................ccaaaffffaaaaaffffaaaacc...................
    ....................ccaaaff1faaaaaff1faaaaac...................
    ....................ccaaaf1ffaaaaaf1ffaaaaac...................
    ....................ccaaaffffaaaaaffffaaaaac...................
    ....................ccaaaaaaaaaaaaaaaaaaaaac...................
    ....................ccaaaaaaaaaaaaaaaaaaaaac...................
    .....................caaaaaaaaaaaaaaaaaaaaac...................
    .....................cfaafffffffffffffaaaacc...................
    .....................cfaafffffffffffffaaaacc...................
    .....................cfaafffffffffffffaaccccc..................
    ....................ccffaaafffffffffaaaccaaacc.................
    ....................caaffaaaaaaaaaaaaaacfaaccccc...............
    ...................ccaaaffaaaaaaaaaaaaffaaacccccc..............
    ...................acaaaafffaaaaaaaaffaaaaacccccc..............
    ..................caccaaaaafffffffffffaaaaaaccccca.............
    ..................caacaaaaaaaa55555555aaaaaaccccca.............
    .................ccaacaaaaaaaa55555555aaaaaaccccca.............
    ................ccaaacaaaaaaaaaa5555aaaaaaaaccccca.............
    ...............ccaaaacaaaaaaaaaaaaaaaaaaaaaacccccca............
    ...............caaaacaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............ccaaaccaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............caccccaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaa.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaaaacccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ................ccccaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaa..........
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    `,img`
    ...............................................................
    ...........................cccccccccc..........................
    .........................cccaaaaaaaaccc........................
    ........................ccaaaaaaaaaaaacc.......................
    .......................ccaaaaaaaaaaaaaacc......................
    ......................ccaaaaaaaaaaaaaaaacc.....................
    ......................caaaaaaaaaaaaaaaaaac.....................
    .....................ccaaaaaaaaaaaaaaaaaacc....................
    .....................ccaaaaaaaaaaaaaaaaaaac....................
    .....................caaaaaaaaaaaaaaaaaaaac....................
    ....................ccaaaaaaaaaaaaaaaaaaaacc...................
    ....................ccaaaffffaaaaaffffaaaacc...................
    ....................ccaaaff1faaaaaff1faaaaac...................
    ....................ccaaaf1ffaaaaaf1ffaaaaac...................
    ....................ccaaaffffaaaaaffffaaaaac...................
    ....................ccaaaaaaaaaaaaaaaaaaaaac...................
    ....................ccaaaaaaaaaaaaaaaaaaaaac...................
    .....................caaaaaaaaaaaaaaaaaaaaac...................
    .....................cfaafffffffffffffaaaacc...................
    .....................cfaafffffffffffffaaaacc...................
    .....................cfaafffffffffffffaaccccc..................
    .....................cffaaafffffffffaaaccaaccc.................
    ....................caaffaaaaaaaaaaaaaacfaaccccc...............
    ...................ccaaaffaaaaaaaaaaaaffaaacccccc..............
    ...................accaaafffaaaaaaaaffaaaaaaccccc..............
    ..................caacaaaaafffffffffffaaaaaaccccca.............
    ..................caacaaaaaaaa55555555aaaaaaccccca.............
    .................ccaacaaaaaaaaaa5555aaaaaaaaccccca.............
    ................ccaaacaaaaaaaaaaaaaaaaaaaaaaccccca.............
    ...............ccaaacaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ...............caaaacaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccca............
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccca...........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaacccccccca..........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............caaaacaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............caccccaaaaaaaaaaaaaaaaaaaaaaaaccccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaa.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ..............ccaaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ...............caaacaaaaaaaaaaaaaaaaaaaaaaacacccccccca.........
    ................ccccaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaa..........
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaaaaaaaaaaaaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    ....................aaaaaaaaaa........aaaaacccccc..............
    `],
1000,
true
)
mySprite2.setPosition(80, 80)
mySprite.setVelocity(50, 0)
mySprite = sprites.create(img`
    .......111.......
    .111..1fff1..111.
    1eee111fff111eee1
    1e44eefffffee44e1
    1e4eeeeeeeeeee4e1
    .1eefffeeefffee1.
    ..1f111fef111f1..
    .1ef181fef181fe1.
    .1ef111fef111fe1.
    .14444fffff44441.
    144f444fff444f441
    14f44444444444f41
    1444f4444444f4441
    .1f11f11f11f11f1.
    .1fffffffffffff1.
    .1f11f11f11f11f1.
    .1eeeeeeeeeeeee1.
    ..1eeeeeeeeeee1..
    ...11111111111...
    `, SpriteKind.Player)
mySprite.setPosition(80, 10)
controller.moveSprite(mySprite, 50, 50)
mySprite.setStayInScreen(true)
the_REAL_Freddy = sprites.create(img`
    ...............................................................
    ...............................................................
    ...............................................................
    ............................11111111...........................
    ...........................1ffffffff1..........................
    ...........................1ffffffff1..........................
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee111ffffffff111eeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeffffffffeeeefffffffeee.............
    .....................eeeeeeeffffffffeeeefffffff................
    ..eeeeeeeeeeeee......eeeeeeeffffffffeeeffffffffeeeeeeeeeeeee...
    ..eeeeeeeeeeeee......eeeeeeeeeeefffffffffffee..eeeeeeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeeeeefffffffffffee..eefffeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeeebbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeebbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeeebfeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeffffffffeeeffffffffeeeffeeeeeeee...
    ......bbbbb.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...bbbbb.....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ......bbbbb.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...bbbbb.....
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeeeeeeeeeeeeeee.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee.......bbbbbbbb........bbbbbbb.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee...............
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeee...eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeee....eeeeeeeeeeee...............
    ...................eeeeeeeeeeeee....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    .......................eeeee........eeeeeeeeee.................
    .......................eeeee............eeeee..................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    ........................eeeee..........eeeee...................
    .........................eeeeeeee.......eeeeeeeeee.............
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    `, SpriteKind.Ally)
the_REAL_Freddy.setPosition(-30, 70)
animation.runImageAnimation(
the_REAL_Freddy,
[img`
    ...............................................................
    ...............................................................
    ...............................................................
    ............................11111111...........................
    ...........................1ffffffff1..........................
    ...........................1ffffffff1..........................
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee111ffffffff111eeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeffffffffeeeefffffffeee.............
    .....................eeeeeeeffffffffeeeefffffff................
    ..eeeeeeeeeeeee......eeeeeeeffffffffeeeffffffffeeeeeeeeeeeee...
    ..eeeeeeeeeeeee......eeeeeeeeeeefffffffffffee..eeeeeeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeeeeefffffffffffee..eefffeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeeebbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeebbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeeebfeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeffffffffeeeffffffffeeeffeeeeeeee...
    ......bbbbb.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...bbbbb.....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ......bbbbb.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...bbbbb.....
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeeeeeeeeeeeeeee.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee.......bbbbbbbb........bbbbbbb.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee...............
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeee...eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeee....eeeeeeeeeeee...............
    ...................eeeeeeeeeeeee....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    .......................eeeee........eeeeeeeeee.................
    .......................eeeee............eeeee..................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    ........................eeeee..........eeeee...................
    .........................eeeeeeee.......eeeeeeeeee.............
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    `,img`
    ...............................................................
    ...............................................................
    ...............................................................
    ............................11111111...........................
    ...........................1ffffffff1..........................
    ...........................1ffffffff1..........................
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee111ffffffff111eeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeffffffffeeeefffffffeee.............
    .....................eeeeeeeffffffffeeeefffffff................
    ..eeeeeeeeeeeee......eeeeeeeffffffffeeeffffffffeeeeeeeeeeeee...
    ..eeeeeeeeeeeee......eeeeeeeeeeefffffffffffee..eeeeeeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeeeeefffffffffffee..eefffeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeeebbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeebbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeeebfeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeffffffffeeeffffffffeeeffeeeeeeee...
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeeeeeeeeeeeeeee.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee.......bbbbbbbb.....eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee...............
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeee...eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeee....eeeeeeeeeeee...............
    ...................eeeeeeeeeeeee....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    .......................eeeee............eeeee..................
    .......................eeeee.........eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    .....................eeeeeeeee.........eeeee...................
    ........................eeeee...........eeeeeeeeee.............
    .........................eeeeeeee..eeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeee............................
    `,img`
    ...............................................................
    ...............................................................
    ...............................................................
    ............................11111111...........................
    ...........................1ffffffff1..........................
    ...........................1ffffffff1..........................
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee111ffffffff111eeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeffffffffeeeefffffffeee.............
    .....................eeeeeeeffffffffeeeefffffff................
    ..eeeeeeeeeeeee......eeeeeeeffffffffeeeffffffffeeeeeeeeeeeee...
    ..eeeeeeeeeeeee......eeeeeeeeeeefffffffffffee..eeeeeeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeeeeefffffffffffee..eefffeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeeebbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeebbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeeebfeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeffffffffeeeffffffffeeeffeeeeeeee...
    ......bbbbb.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...bbbbb.....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ......bbbbb.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...bbbbb.....
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeeeeeeeeeeeeeee.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee.......bbbbbbbb........bbbbbbb.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee...............
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeee...eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeee....eeeeeeeeeeee...............
    ...................eeeeeeeeeeeee....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    .......................eeeee........eeeeeeeeee.................
    .......................eeeee............eeeee..................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    ........................eeeee..........eeeee...................
    .........................eeeeeeee.......eeeeeeeeee.............
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    `,img`
    ...............................................................
    ...............................................................
    ...............................................................
    ............................11111111...........................
    ...........................1ffffffff1..........................
    ...........................1ffffffff1..........................
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee..1ffffffff1..eeeeeeeeeee.............
    ..............eeeeeeeeeee111ffffffff111eeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeffffffffffffffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeefffffffeeeeeeefffffffeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeefffffffffffeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    ..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
    .................eeeeeeeeeeeffffffffeeeefffffffeee.............
    .....................eeeeeeeffffffffeeeefffffff................
    ..eeeeeeeeeeeee......eeeeeeeffffffffeeeffffffffeeeeeeeeeeeee...
    ..eeeeeeeeeeeee......eeeeeeeeeeefffffffffffee..eeeeeeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeeeeefffffffffffee..eefffeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeebbbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeeeeefffffffffffeeeebbbbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeebbfeeeeeeee...
    ..eeeeeeeeeeeeebeeeeeeeeeeeeffffffffeeeffffffffeeebfeeeeeeee...
    ..eeeeeeeeeeeee.eeeeeeeeeeeeffffffffeeeffffffffeeeffeeeeeeee...
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeefffffeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    ....eeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeee....
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
    .eeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeeeeeeeeeeeeeee.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee....eeeeeeeeeeeeee.....bbbbbbb.....eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeee..eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee..eeeeeeeeeeee.
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee...............
    .eeeeeeeeeeeeee...eeeeeeeeeeeeeeee.eeeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee.eeeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeeee..eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeeee...eeeeeeeeeeee...............
    ..................eeeeeeeeeeeeee....eeeeeeeeeeee...............
    ...................eeeeeeeeeeeee....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeeeee...............
    ....................eeeeeeeeeee.....eeeeeeeeee.................
    .......................eeeee........eeeeeeeeee.................
    .......................eeeee........eeeeeeeeee.................
    ....................eeeeeeeeeee.........eeeee..................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    ....................eeeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeeee......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    .....................eeeeeeeee.......eeeeeeeeee................
    ........................eeeee........eeeeeeeeee................
    .........................eeeeeeee......eeeee...................
    ....................eeeeeeeeeeeeeee.....eeeeeeeeee.............
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
    ...................................eeeeeeeeeeeeeeeee...........
    `],
1000,
false
)
mySprite3 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, 0)
mySprite4 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, 0)
pause(2000)
mySprite2.sayText("Hello", 2000, true)
pause(3000)
mySprite2.sayText("would you like to talk to me?", 2500, true)
pause(3500)
mySprite3 = sprites.create(img`
    1.....1.1111111...11111..
    1.....1.1........1.....1.
    1.....1.1.......1.......1
    .1...1..1.......1........
    .1...1..1.......1........
    ..1.1...1.......1........
    ..1.1...1........1.......
    ...1....1111......11111..
    ...1....1..............1.
    ...1....1...............1
    ...1....1...............1
    ...1....1...............1
    ...1....1...............1
    ...1....1.......1.......1
    ...1....1........1.....1.
    ...1....1111111...11111..
    `, SpriteKind.YES_alternative)
mySprite4 = sprites.create(img`
    11.......1.....11111111....
    111......1....1111111111...
    1.1......1...11........11..
    1.11.....1..11..........11.
    1..1.....1.11............11
    1..11....1.11............11
    1...1....1.11............11
    1...11...1.11............11
    1....1...1.11............11
    1....11..1.11............11
    1.....1..1.11............11
    1.....11.1.11............11
    1......1.1..11..........11.
    1......111...11........11..
    1.......11....1111111111...
    1.......11.....11111111....
    `, SpriteKind.NO_alternative)
mySprite3.setPosition(60, 110)
mySprite4.setPosition(106, 110)
